feat: reusable button component
tomershvueli/expert-event-solutions pull request #5
Opened 2024-08-24 02:33 UTC by Marcelluki

## Describe your changes
- Created Button.tsx for Reusable button component
- added Button.css for styling
- Button accepts variants 

## Issue ticket number and link
https://tripleten-apiary.atlassian.net/browse/EES-11
EES-11

## Checklist before requesting a review

- [ ] I have performed a self-review of my code
- [ ] If there are changes to components, I have added / updated automated tests
- [ ] I have made any necessary updates to Storybook to accompany these changes
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings

2024-08-25 13:45 UTC, RPinkha requested changes
No tailwind used. 
No button.css for styling that can't be achieved with tailwind.

2024-08-25 13:45 UTC, RPinkha commented on src/main.tsx
>    uri: "http://localhost:8080/api/graphql",
URL is misspelled.

2024-08-25 13:45 UTC, RPinkha commented on src/main.tsx
> +        <Button submit={console.log} buttonText={"Contact Us!"}/>
The button text doesn't seem to be reusable

2024-08-27 12:52 UTC, XDRO requested changes
You must ensure that you have the Button component uploaded to Github. You are still failing Github test, from line 6.

2024-08-27 12:52 UTC, XDRO commented on src/main.tsx
> +import { Button } from "./components/Button/Button";
There is still an issue with Github tests, please ensure that the './components/Button/Button is the correct path.

2024-08-27 12:52 UTC, XDRO commented on src/main.tsx
> +import { Button } from "./components/Button/Button";
I notice that there is not a Button folder, file, or component when I switch to this branch. As it is not present in the repo on Github.

2024-09-12 16:46 UTC, closed without merging